---
- name: deploy nginx docker container 
  hosts: all
  become: yes
  gather_facts: no
  vars_files: vault.yml
  tasks:
    - name: "Include ansible-sample"
      include_role:
        name: "ansible_sample"